baseURL = "https://nullsum.net"
languageCode = "en-us"
title = "nullsum.net"
copyright = "Copyright Â© 2018-{year} Andrew Rabert"

pygmentsUseClasses=true

[params]
homeText = "Personal blog of Andrew Rabert"
